
# How to do OS independent file paths?
[spatialitedatabase]
    filepath = "/somefile.db"

[background]
    color = "0,0,255"

[[layer]]
    name = "Cities"
    type = "vector"
    geometry_type = "point"
    fill_color = "0,0,255"
    outline_color = "0,0,255"
    thickness = 1

    [layer.source]
        type = "sql"

[[layer]]
    # name = "Train Stations"
    type = "vector"
    geometry_type = "point"
    fill_color = "255,0,0"
    outline_color = "0,0,255"
    thickness = 1

    [layer.source]
        type = "shapefile"


[[layer]]
    name = "Manhole covers"
    type = "vector"
    geometry_type = "point"
    fill_color = "255,0,0"
    outline_color = "0,0,255"
    thickness = 1

    [layer.source]
        type = "shapefile"